'use client';

// Import the named export from your showcase template
// Adjust the import path as needed
import React, { FC, useRef } from 'react';
import { motion, useMotionValue, useSpring, useTransform } from 'framer-motion'; // Import motion and hooks

// --- 1. Define the component to be previewed ---

export const SpotlightCard: FC = () => {
    const cardRef = useRef<HTMLDivElement>(null);

    // Motion values to track the mouse position relative to the card
    const mouseX = useMotionValue(0);
    const mouseY = useMotionValue(0);

    // Spring physics for a smooth, lagging effect
    const springConfig = { damping: 25, stiffness: 400, mass: 0.5 };
    const smoothMouseX = useSpring(mouseX, springConfig);
    const smoothMouseY = useSpring(mouseY, springConfig);

    const handleMouseMove = (e: React.MouseEvent<HTMLDivElement>) => {
        if (cardRef.current) {
            const { left, top } = cardRef.current.getBoundingClientRect();
            mouseX.set(e.clientX - left);
            mouseY.set(e.clientY - top);
        }
    };

    return (
        <motion.div
            ref={cardRef}
            className="group relative w-full max-w-md h-64 p-6 bg-slate-900/50 border border-slate-800 rounded-xl shadow-lg overflow-hidden"
            onMouseMove={handleMouseMove}
        >
            {/* The Spotlight Effect */}
            <motion.div
                className="absolute inset-0 pointer-events-none"
                style={{
                    background: useTransform(
                        [smoothMouseX, smoothMouseY],
                        ([x, y]) => `radial-gradient(circle 200px at ${x}px ${y}px, rgba(14, 165, 233, 0.15), transparent 80%)`
                    ),
                }}
            />

            {/* Card Content */}
            <div className="relative z-10">
                <h3 className="text-2xl font-bold text-slate-200 mb-2">Spotlight Card</h3>
                <p className="text-slate-400">
                    Move your cursor over this card. The glowing spotlight is generated by a radial gradient that follows your mouse position.
                </p>
            </div>
        </motion.div>
    );
};


// --- 2. Define the code string for the component ---
export const spotlightCardCodeString = `
'use client';

import React, { FC, useRef } from 'react';
import { motion, useMotionValue, useSpring, useTransform } from 'framer-motion';

const SpotlightCard: FC = () => {
    const cardRef = useRef<HTMLDivElement>(null);

    const mouseX = useMotionValue(0);
    const mouseY = useMotionValue(0);

    const springConfig = { damping: 25, stiffness: 400, mass: 0.5 };
    const smoothMouseX = useSpring(mouseX, springConfig);
    const smoothMouseY = useSpring(mouseY, springConfig);

    const handleMouseMove = (e: React.MouseEvent<HTMLDivElement>) => {
        if (cardRef.current) {
            const { left, top } = cardRef.current.getBoundingClientRect();
            mouseX.set(e.clientX - left);
            mouseY.set(e.clientY - top);
        }
    };

    return (
        <motion.div
            ref={cardRef}
            className="group relative w-full max-w-md h-64 p-6 bg-slate-900/50 border border-slate-800 rounded-xl shadow-lg overflow-hidden"
            onMouseMove={handleMouseMove}
        >
            {/* The Spotlight Effect */}
            <motion.div
                className="absolute inset-0 pointer-events-none"
                style={{
                    background: useTransform(
                        [smoothMouseX, smoothMouseY],
                        ([x, y]) => \`radial-gradient(circle 200px at \${x}px \${y}px, rgba(14, 165, 233, 0.15), transparent 80%)\`
                    ),
                }}
            />

            {/* Card Content */}
            <div className="relative z-10">
                <h3 className="text-2xl font-bold text-slate-200 mb-2">Spotlight Card</h3>
                <p className="text-slate-400">
                    Move your cursor over this card. The glowing spotlight is generated by a radial gradient that follows your mouse position.
                </p>
            </div>
        </motion.div>
    );
};

export default SpotlightCard;
`;