"use client";

import React, { FC, useRef } from "react";
import { motion, useMotionValue, useSpring, useTransform } from "framer-motion";
import { cn } from './utils';

interface SpotlightCardProps {
  title?: string;
  description?: string;
  className?: string;
}

export const SpotlightCard: FC<SpotlightCardProps> = ({
  title = "Spotlight Card",
  description = "Move your cursor over this card. The glowing spotlight is generated by a radial gradient that follows your mouse position.",
  className,
}) => {
  const cardRef = useRef<HTMLDivElement>(null);

  const mouseX = useMotionValue(0);
  const mouseY = useMotionValue(0);

  const springConfig = { damping: 25, stiffness: 400, mass: 0.5 };
  const smoothMouseX = useSpring(mouseX, springConfig);
  const smoothMouseY = useSpring(mouseY, springConfig);

  const handleMouseMove = (e: React.MouseEvent<HTMLDivElement>) => {
    if (cardRef.current) {
      const { left, top } = cardRef.current.getBoundingClientRect();
      mouseX.set(e.clientX - left);
      mouseY.set(e.clientY - top);
    }
  };

  return (
    <motion.div
      ref={cardRef}
      className={cn(
        "group relative w-full max-w-md h-64 p-6 bg-slate-900/50 border border-slate-800 rounded-xl shadow-lg overflow-hidden",
        className
      )}
      onMouseMove={handleMouseMove}
    >
      <motion.div
        className="absolute inset-0 pointer-events-none"
        style={{
          background: useTransform(
            [smoothMouseX, smoothMouseY],
            ([x, y]) =>
              `radial-gradient(circle 200px at ${x}px ${y}px, rgba(14, 165, 233, 0.15), transparent 80%)`
          ),
        }}
      />

      <div className="relative z-10">
        <h3 className="text-2xl font-bold text-slate-200 mb-2">
          {title}
        </h3>
        <p className="text-slate-400">
          {description}
        </p>
      </div>
    </motion.div>
  );
};

export default SpotlightCard;
